---
title: napoleon3
max_points: 2
instructions: |
  <p>  </p>
  <p>
    <iframe src="../_static/ggframe.html" id="napoleon3_frame" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>
    <script type="text/javascript">
      function postMsg() {
        var napoleon3Frame = document.getElementById("napoleon3_frame");        napoleon3Frame.contentWindow.postMessage( '' + '´´´' + '{"appName" : "graphing", "height" : 600, "showMenuBar" : true, "showAlgebraInput" : true, "showToolBar" : true, "customToolBar" : "0 77 73 62 | 1 501 67 , 5 19 , 72 75 76 | 2 15 45 , 18 65 , 7 37 | 4 3 8 9 , 13 44 , 58 , 47 | 16 51 64 , 70 | 10 34 53 11 , 24  20 22 , 21 23 | 55 56 57 , 12 | 36 46 , 38 49  50 , 71  14  68 | 30 29 54 32 31 33 | 25 17 26 60 52 61 | 40 41 42 , 27 28 35 , 6", "showToolBarHelp" : true, "showResetIcon" : true, "enableLabelDrags" : false, "enableShiftDragZoom" : true, "enableRightClick" : true, "errorDialogsActive" : false, "useBrowserForJS" : false, "allowStyleBar" : true, "preventFocus" : true, "showZoomButtons" : true, "capturingThreshold" : 3, "language" : "fi"}' , '*');
        document.getElementById("napoleon3_id").style.display = "none";
      };
    </script>
  </p>
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: napoleon3
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh ggb-element