---
title: releaux_piirto
max_points: 2
instructions: |
  <p>  </p>
  <p>
    <iframe src="../_static/ggframe.html" id="releaux_piirto_frame" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>
    <script type="text/javascript">
      function postMsg() {
        var releaux_piirtoFrame = document.getElementById("releaux_piirto_frame");        releaux_piirtoFrame.contentWindow.postMessage( '!! \n javascript: |!! \n P.setDataInit = function (api, geostate) { \n     timgeo.setState(api, geostate); \n } \n  \n P.getData = function(){ \n     return { \n        "data": ggbApplet.getBase64() \n    }; \n } \n  \n P.appName = "geometry"; \n P.showToolbar = true; \n P.language = "fi"' + '´´´' + '{"appName" : "geometry", "showToolbar" : true}' , '*');
        document.getElementById("releaux_piirto_id").style.display = "none";
      };
    </script>
  </p>
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: releaux_piirto
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh ggb-element