---
title: geo_kolmioiden_piirto1
max_points: 2
instructions: |
  <p>  </p>
  <p>
    <iframe src="../_static/ggframe.html" id="geo_kolmioiden_piirto1_frame" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>
    <script type="text/javascript">
      function postMsg() {
        var geo_kolmioiden_piirto1Frame = document.getElementById("geo_kolmioiden_piirto1_frame");        geo_kolmioiden_piirto1Frame.contentWindow.postMessage( 'A: (0, 0) \n B: A + (6; 0) \n C: A + (3; 60°) \n k1: Polygon[A, B, C] \n c: Segment[A, B, k1] \n a: Segment[B, C, k1] \n b: Segment[C, A, k1] \n α: Angle(A,C,B) \n β: Angle(C,B,A) \n γ: Angle(B,A,C) \n D: (-2, 0) \n E: D + (4.5; 180°) \n f: Segment[D, E] \n SetLabelMode(a,2) \n SetLabelMode(b,2) \n SetLabelMode(c,2) \n SetLabelMode(f,2) \n ShowLabel(a,true) \n ShowLabel(b,true) \n ShowLabel(c,true) \n ShowLabel(f,true) \n ZoomIn(-7.7,-8.4,7.5,11.8)' + '´´´' + '{"appName" : "geometry", "showAlgebraInput" : true, "showToolBar" : true, "showToolBarHelp" : true, "showResetIcon" : true, "errorDialogsActive" : false, "allowStyleBar" : true, "showZoomButtons" : true, "language" : "fi"}' , '*');
        document.getElementById("geo_kolmioiden_piirto1_id").style.display = "none";
      };
    </script>
  </p>
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: geo_kolmioiden_piirto1
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh ggb-element