---
title: kolmion_sivu
max_points: 2
instructions: |
  <p>  </p>
  <p>
    <iframe src="../_static/ggframe.html" id="kolmion_sivu_frame" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>
    <script type="text/javascript">
      function postMsg() {
        var kolmion_sivuFrame = document.getElementById("kolmion_sivu_frame");        kolmion_sivuFrame.contentWindow.postMessage( '!! \n javascript: |!! \n P.setDataInit = function (api, geostate) { \n     timgeo.setState(api, geostate); \n } \n  \n P.getData = function(){ \n     let api = ggbApplet; \n     let vastaus = api.getValue("a"); \n     let mallivastaus = Math.sqrt(5*5+7*7-2*5*7*Math.cos(72*Math.PI/180)); \n     let maxpoints = 2;    \n     let points = 0; \n     if ( Math.round(vastaus*100)/100 == Math.round(mallivastaus*100)/100 ) points = maxpoints;  \n     return { \n        "usercode": ggbApplet.getValue('a'), \n        "userpts":  timgeo.getObjValue(ggbApplet,"a"), \n        "data": ggbApplet.getBase64(), \n        "points": points,  \n    }; \n } \n P.language = "fi"; \n P.appName = "geometry"; \n P.showToolbar = true; \n P.showAlgebraInput = true; \n P.allowStyleBar = true;' + '´´´' + '{"language" : "fi", "appName" : "geometry", "showToolbar" : true, "showAlgebraInput" : true, "allowStyleBar" : true}' , '*');
        document.getElementById("kolmion_sivu_id").style.display = "none";
      };
    </script>
  </p>
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: kolmion_sivu
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh ggb-element