---
title: denny
max_points: 2
instructions: |
  <p>  </p>
  <p>
    <iframe src="../_static/ggframe.html" id="denny_frame" onload="postMsg();" width="1000" height="600" frameborder="0"></iframe>
    <script type="text/javascript">
      function postMsg() {
        var dennyFrame = document.getElementById("denny_frame");        dennyFrame.contentWindow.postMessage( '' + '´´´' + '{"material_id" : "mwkny4tc", "showMenuBar" : true, "showToolBar" : true, "enableShiftDragZoom" : true, "language" : "fi", "perspective" : "2"}' , '*');
        document.getElementById("denny_id").style.display = "none";
      };
    </script>
  </p>
view_type: access.types.stdasync.acceptPost 
fields: # näiden täytyy olla valideja HTML-formien attribuutteja
  - name: denny
    required: True

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/geogebra-example
  cmd: /exercise/run.sh ggb-element